### ISSUE TITLE
Very minor typo

### ISSUE THREAD

**Issue by henrikjacobsenfys** [tsdev/spinw#34]
Hi Sandor!
This is probably the smallest, most insignificant thing I will ever report, and I feel petty just for typing it, but I thought I might as well :)

in sw_neutron line 148 the warning says

warning('sw_neutron:ScatteringPlaneProblem','The normal to the scattering plane is not perpendiculat to Q!');

It should be perpendicular, not perpendiculat

**Comment by tsdev** [comment]
Thanks! Any bug matters!
Fixed in master branch!
If you fork the repository, you can also make pull requests to add corrections to SpinW.
