### ISSUE TITLE
New preference class needs Matlab 2017a

### ISSUE THREAD

**Issue by mducle** [tsdev/spinw#56]
The new `swpref` class uses the built-in functions `mustBeInteger`,  `mustBeNonNegative`, `mustBeGreaterThan` and `mustBeLessThan` which were introduced in Matlab 2017a.

Is Matlab 2017 or newer now a requirement?

**Comment by wardsimon** [comment]
No, 2017a is not a requirement. I just forgot to test against earlier versions. 
I fixed this in the new SpinW organisation [https://github.com/SpinW/spinw](https://github.com/SpinW/spinw ) . I'll make a pull request here as well so all code bases are up to date.

**Comment by mducle** [comment]
Ah ok. Sorry I didn't realise that there was a new repository.
